spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: platform
  datasource:
    url: jdbc:postgresql://localhost:5432/platform
    username: postgres
    password: qwerty007
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        auto_quote_keyword: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        query:
          plan:
            cache:
              max_size: 100
          cache:
            region:
              factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
            use_second_level_cache: true
            use_query_cache: true

key:
  access: Qiv2P1iotfT2jbZ/BoxzqmeoQ0jZSpFRoNbtl8fdA7U=
  refresh: 5paNuOHQTD/J9D6pcJvZfu+rqgqaCCZNZQrgmXdSo8c=

